### ISSUE TITLE
Feature request: Add lodash

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/trame-client#1]
Could be useful to add the [lodash](https://github.com/lodash/lodash) library, so we could use it in click events like `utils.download` from Trame.

Lodash makes it easy to work with arrays, numbers, objects, strings, etc., so I think it'd fit right into the Trame eco-system to make functions shorter and more simple.

Something like:

```py
vuetify.VBtn(
    "Click Me",
    click=(print, "[lodash.range(0, 10, 2)]"),
)
```

**Comment by jourdain** [comment]
This could be added at the application level via cdn or added to utils on a module load (which could be part of the client).
I would definitely make it optional and up to the user to bring it on. This is very JS specific and I'm not sure it will be widely used. Your example is also not very convincing.

**Comment by jourdain** [comment]
```python
# ...
server.enable_module(dict(scripts=["https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"]))

# Then on the JS side you can use `_.range(0, 10, 2)`

```
